const API_BASE = (import.meta.env?.VITE_API_URL || 'http://localhost:3000/api').replace(/\/$/, '');
let db={users:[],orgs:[],products:[],session:null}, page='dashboard', editingId=null, search='', liveFeed=null;
async function api(path,options={}){const response=await fetch(`${API_BASE}${path}`,{credentials:'include',headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'Something went wrong.');return data}
function hydrate(data){if(!data.user){db={users:[],orgs:[],products:[],session:null};return}db={users:[data.user],orgs:[data.org],products:data.products,session:data.user.id}}
async function refresh(silent=true){try{hydrate(await api('/session'));render()}catch(e){if(!silent)toast(e.message)}}
async function bootstrap(){document.querySelector('#app').innerHTML='<div class="empty"><div class="empty-icon">▰</div><h3>Loading StockFlow…</h3></div>';await refresh();connectLive()}
function connectLive(){liveFeed?.close();if(!currentUser())return;liveFeed=new EventSource(`${API_BASE}/events`, { withCredentials: true });liveFeed.addEventListener('refresh',()=>refresh())}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return v===''||v==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v)}
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function currentUser(){return db.users.find(u=>u.id===db.session)}
function currentOrg(){const u=currentUser();return u&&db.orgs.find(o=>o.id===u.orgId)}
function products(){const o=currentOrg();return o?db.products.filter(p=>p.orgId===o.id):[]}
function threshold(p){return p.lowStockThreshold===''||p.lowStockThreshold==null?currentOrg().defaultThreshold:Number(p.lowStockThreshold)}
function isLow(p){return Number(p.quantity)<=threshold(p)}

function render(){document.querySelector('#app').innerHTML=currentUser()?appView():authView();bind()}
function authView(){return `<div class="auth-shell"><section class="auth-art"><div class="brand"><span class="brand-mark">▰</span> StockFlow</div><div class="auth-copy"><h1>Inventory clarity,<br>without the clutter.</h1><p>Track every product, spot low stock early, and keep your business moving—all from one beautifully simple workspace.</p></div><div class="proof"><div><b>Simple</b>Built for focus</div><div><b>Fast</b>Ready in minutes</div><div><b>Secure</b>Your data, separated</div></div></section><main class="auth-panel"><div class="auth-box" id="auth-box">${loginForm()}</div></main></div>`}
function loginForm(){return `<h2>Welcome back</h2><p class="sub">Sign in to continue to your inventory.</p><form id="login-form"><div class="field"><label>Email address</label><input name="email" type="email" placeholder="you@company.com" required></div><div class="field"><label>Password</label><input name="password" type="password" placeholder="Enter your password" required></div><div class="error" id="auth-error"></div><button class="btn btn-primary btn-block">Sign in</button></form><p class="auth-switch">New to StockFlow? <button class="link-btn" data-auth="signup">Create an account</button></p>`}
function signupForm(){return `<h2>Create your account</h2><p class="sub">Start organizing your inventory today.</p><form id="signup-form"><div class="field"><label>Organization name</label><input name="org" placeholder="My Store" required></div><div class="field"><label>Email address</label><input name="email" type="email" placeholder="you@company.com" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="6" placeholder="At least 6 characters" required></div><div class="field"><label>Confirm password</label><input name="confirm" type="password" placeholder="Repeat your password" required></div><div class="error" id="auth-error"></div><button class="btn btn-primary btn-block">Create workspace</button></form><p class="auth-switch">Already have an account? <button class="link-btn" data-auth="login">Sign in</button></p>`}
function appView(){const u=currentUser(),o=currentOrg();return `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">▰</span> StockFlow</div><nav class="nav">${nav('dashboard','⌂','Dashboard')}${nav('products','▦','Products')}${nav('settings','⚙','Settings')}</nav><div class="user-card"><div class="avatar">${esc(o.name[0].toUpperCase())}</div><div class="user-meta"><b>${esc(o.name)}</b><span>${esc(u.email)}</span></div><button class="logout" title="Log out">↪</button></div></aside><main class="main">${pageView()}</main></div>${editingId!==null?productModal():''}`}
function nav(p,icon,label){return `<button class="nav-btn ${page===p?'active':''}" data-page="${p}"><span>${icon}</span>${label}</button>`}
function header(title,sub,action=''){return `<header class="topbar"><div><h1>${title}</h1><p>${sub}</p></div>${action||`<span class="org-pill">${esc(currentOrg().name)}</span>`}</header>`}
function pageView(){if(page==='products')return productsView();if(page==='settings')return settingsView();return dashboardView()}
function dashboardView(){const ps=products(),low=ps.filter(isLow),value=ps.reduce((s,p)=>s+Number(p.quantity)*(Number(p.costPrice)||0),0);return `${header('Dashboard','Here’s what’s happening with your inventory today.')}<section class="stats"><div class="card stat"><div class="stat-top"><span>Total products</span><i class="stat-icon">▦</i></div><h3>${ps.length}</h3><small>Active inventory items</small></div><div class="card stat"><div class="stat-top"><span>Units on hand</span><i class="stat-icon">▤</i></div><h3>${ps.reduce((s,p)=>s+Number(p.quantity),0)}</h3><small>Across all products</small></div><div class="card stat"><div class="stat-top"><span>Inventory value</span><i class="stat-icon">₹</i></div><h3>${money(value)}</h3><small>Based on cost price</small></div></section><section class="card section-card"><div class="section-head"><div><h2>Low stock items</h2><p>Products at or below their reorder threshold</p></div><button class="btn btn-secondary btn-sm" data-page="products">View all</button></div>${low.length?productTable(low,true):empty('✓','Everything looks stocked','No products are currently below their threshold.')}</section>`}
function productsView(){const filtered=products().filter(p=>(p.name+' '+p.sku).toLowerCase().includes(search.toLowerCase()));return `${header('Products',`${products().length} products in your inventory`,`<button class="btn btn-primary" id="add-product">＋ Add product</button>`)}<div class="toolbar"><div class="search"><span>⌕</span><input id="search" value="${esc(search)}" placeholder="Search by name or SKU..."></div></div><section class="card section-card">${filtered.length?productTable(filtered,false):empty('▦',search?'No matching products':'Your inventory is empty',search?'Try a different name or SKU.':'Add your first product to get started.')}</section>`}
function productTable(ps,compact){return `<div class="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Quantity</th><th>Status</th><th class="hide-mobile">Selling price</th>${compact?'':'<th></th>'}</tr></thead><tbody>${ps.map(p=>`<tr><td><span class="product-name">${esc(p.name)}</span></td><td><span class="sku">${esc(p.sku)}</span></td><td><b>${p.quantity}</b></td><td>${isLow(p)?'<span class="badge badge-low"><i class="dot"></i>Low stock</span>':'<span class="badge badge-ok"><i class="dot"></i>In stock</span>'}</td><td class="hide-mobile">${money(p.sellingPrice)}</td>${compact?'':`<td><div class="actions"><button class="icon-btn edit" data-id="${p.id}" title="Edit">✎</button><button class="icon-btn delete" data-id="${p.id}" title="Delete">×</button></div></td>`}</tr>`).join('')}</tbody></table></div>`}
function empty(icon,title,text){return `<div class="empty"><div class="empty-icon">${icon}</div><h3>${title}</h3><div>${text}</div></div>`}
function settingsView(){return `${header('Settings','Manage your organization preferences.')}<section class="settings"><div class="card"><h2>Inventory preferences</h2><p>This threshold is used when a product does not have its own custom value.</p><form id="settings-form" class="settings-row"><div class="field"><label>Default low stock threshold</label><input name="threshold" type="number" min="0" step="1" value="${currentOrg().defaultThreshold}" required></div><button class="btn btn-primary">Save changes</button></form></div></section>`}
function productModal(){const p=editingId==='new'?{}:db.products.find(x=>x.id===editingId);return `<div class="modal-backdrop"><form class="modal" id="product-form"><div class="modal-head"><h2>${p.id?'Edit product':'Add a new product'}</h2><button type="button" class="close">×</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>Product name *</label><input name="name" value="${esc(p.name||'')}" placeholder="e.g. Classic T-shirt" required></div><div class="field"><label>SKU *</label><input name="sku" value="${esc(p.sku||'')}" placeholder="e.g. TSH-001" required></div><div class="field span-2"><label>Description</label><textarea name="description" placeholder="Optional product details">${esc(p.description||'')}</textarea></div><div class="field"><label>Quantity on hand *</label><input name="quantity" type="number" min="0" step="1" value="${p.quantity??0}" required></div><div class="field"><label>Low stock threshold</label><input name="lowStockThreshold" type="number" min="0" step="1" value="${p.lowStockThreshold??''}" placeholder="Use default (${currentOrg().defaultThreshold})"><span class="hint">Leave blank to use the organization default.</span></div><div class="field"><label>Cost price (₹)</label><input name="costPrice" type="number" min="0" step="0.01" value="${p.costPrice??''}" placeholder="0.00"></div><div class="field"><label>Selling price (₹)</label><input name="sellingPrice" type="number" min="0" step="0.01" value="${p.sellingPrice??''}" placeholder="0.00"></div></div><div class="error" id="product-error"></div><div class="form-actions"><button type="button" class="btn btn-secondary close">Cancel</button><button class="btn btn-primary">${p.id?'Save changes':'Add product'}</button></div></div></form></div>`}

function bind(){
 document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{document.querySelector('#auth-box').innerHTML=b.dataset.auth==='signup'?signupForm():loginForm();bind()});
 document.querySelector('#login-form')?.addEventListener('submit',login);
 document.querySelector('#signup-form')?.addEventListener('submit',signup);
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;search='';render()});
 document.querySelector('.logout')?.addEventListener('click',async()=>{await api('/logout',{method:'POST',body:'{}'});liveFeed?.close();hydrate({user:null});render()});
 document.querySelector('#add-product')?.addEventListener('click',()=>{editingId='new';render()});
 document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{editingId=b.dataset.id;render()});
 document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>removeProduct(b.dataset.id));
 document.querySelectorAll('.close').forEach(b=>b.onclick=()=>{editingId=null;render()});
 document.querySelector('.modal-backdrop')?.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop')){editingId=null;render()}});
 document.querySelector('#product-form')?.addEventListener('submit',saveProduct);
 document.querySelector('#settings-form')?.addEventListener('submit',saveSettings);
 document.querySelector('#search')?.addEventListener('input',e=>{search=e.target.value;const pos=e.target.selectionStart;render();const n=document.querySelector('#search');n.focus();n.setSelectionRange(pos,pos)});
}
async function login(e){e.preventDefault();const f=new FormData(e.target);try{hydrate(await api('/login',{method:'POST',body:JSON.stringify({email:f.get('email').trim(),password:f.get('password')})}));page='dashboard';render();connectLive();toast('Welcome back!')}catch(err){document.querySelector('#auth-error').textContent=err.message}}
async function signup(e){e.preventDefault();const f=new FormData(e.target);if(f.get('password')!==f.get('confirm')){document.querySelector('#auth-error').textContent='Passwords do not match.';return}try{hydrate(await api('/signup',{method:'POST',body:JSON.stringify({org:f.get('org').trim(),email:f.get('email').trim(),password:f.get('password')})}));page='dashboard';render();connectLive();toast('Your workspace is ready!')}catch(err){document.querySelector('#auth-error').textContent=err.message}}
async function saveProduct(e){e.preventDefault();const f=new FormData(e.target),data={name:f.get('name').trim(),sku:f.get('sku').trim(),description:f.get('description').trim(),quantity:Number(f.get('quantity')),lowStockThreshold:f.get('lowStockThreshold')===''?'':Number(f.get('lowStockThreshold')),costPrice:f.get('costPrice')===''?'':Number(f.get('costPrice')),sellingPrice:f.get('sellingPrice')===''?'':Number(f.get('sellingPrice'))};const creating=editingId==='new';try{await api(creating?'/products':`/products/${editingId}`,{method:creating?'POST':'PUT',body:JSON.stringify(data)});editingId=null;await refresh();toast(creating?'Product added':'Product updated')}catch(err){document.querySelector('#product-error').textContent=err.message}}
async function removeProduct(pid){const p=db.products.find(x=>x.id===pid);if(confirm(`Delete “${p.name}”? This cannot be undone.`)){try{await api(`/products/${pid}`,{method:'DELETE'});await refresh();toast('Product deleted')}catch(err){toast(err.message)}}}
async function saveSettings(e){e.preventDefault();try{await api('/settings',{method:'PUT',body:JSON.stringify({threshold:Number(new FormData(e.target).get('threshold'))})});await refresh();toast('Settings saved')}catch(err){toast(err.message)}}
bootstrap();
